### ISSUE TITLE
Bug Reports – XSS Vulnerability Injection has found on SteemDB

### ISSUE THREAD

**Issue by emirfirlar** [aaroncox/steemdb#21]
#### <h1>Expected behavior</h1>
&emsp;
<h3>Defending the Cross Site Scripting (XSS) Attack</h3>

&emsp;

#### <h1>Actual behavior</h1>
&emsp;
<h3>This script is vulnerable to Cross Site Scripting (XSS) attacks.</h3>

&emsp;

#### <h1>How to reproduce</h1>

&emsp;
<center>https://i.hizliresim.com/A1vd5L.jpg</center>
<center>[Source](https://www.owasp.org/images/7/72/OWASP_Top_10-2017_%28en%29.pdf.pdf)</center>
&emsp;

&nbsp;&nbsp;&nbsp; Cross site scripting (XSS) is a vulnerability that allows an attacker to send malicious code (usually in the form of Javascript) to another user. XSS takes part at OWASP PHP Top 5 ([buradan ulaşabilirsiniz](https://www.owasp.org/index.php/PHP_Top_5)). Malicious users may inject JavaScript, VBScript, ActiveX, HTML or Flash into a vulnerable application to fool a user in order to gather data from them. An attacker can take over the account, impersonating the user. 
&emsp;

&nbsp;&nbsp;&nbsp; I wanted to check XSS vulnerability on SteemDB. One of these experiments showed a cookie on the screen. I actually did not expect this. SteemDB could escape previous experiments. Of course it is not good that such important vulnerability was present on steemdb. But I'm sure that @jesta will solve it as soon as possible. 

&emsp;

* You can see how the cookie appears below:

&emsp;

`'https://steemdb.com/posts/all/earnings/2018'"()<acx><script>alert(document.cookie)</script>><marque><h1>XSS'`

&emsp;

https://i.hizliresim.com/Z9aojZ.jpg

&emsp;

&nbsp;&nbsp;&nbsp; I am not a security expert but I could found this vulnerability. I am sure that those who are more expert than me may notice this. I am able to report this vulnerabilitiy through utopian-io and this is good thing. 
&emsp;

* Browser: Firefox Quantum 58.0.2 (32-bit)
* Operating system: Windows 7 professional SP1 (32 bit)
İntel Core 2 Duo 2.13 Ghz , 4 gb RAM
&emsp;

#### Recording Of The Bug
&emsp;
* You can see the XSS  in detail below:    
&emsp;
<center>https://media.giphy.com/media/45a5uKDjFInqWRItY0/giphy.gif</center>
&emsp;
* You can see the source code  in detail below:    
&emsp;
https://i.hizliresim.com/oOa4pm.jpg

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@emirfirlar/bug-reports-xss-vulnerability-injection-has-found-on-steemdb">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by aaroncox** [comment]
This should be resolved now - apologies I didn't get around to this at the time of your posting.

**Comment by emirfirlar** [comment]
no problem, thank you for your interest

**Comment by attritionorg** [comment]
@aaroncox can you link to the fix? Thanks!

**Comment by aaroncox** [comment]
@attritionorg I can't actually, the fix isn't published here (as the github repo and local codebases have diverged). This version of steemdb will be retired at some point (hopefully sooner than later) in favor of a completely new site. Because of that, I haven't wanted to devote the time to bringing this repo up to date.

**Comment by attritionorg** [comment]
@aaroncox understood, thanks!
