### ISSUE TITLE
Installer corrupt Could not open input file: composer-setup.php

### ISSUE THREAD

**Issue by educoin** [aaroncox/steemdb#23]
Hi! 
I am trying to install steemdb on my own server and I've got this error when I run "docker-compose up" 

 ---> Running in bbb96ebac15a
Installer corrupt
Could not open input file: composer-setup.php
ERROR: Service 'development' failed to build: The command '/bin/sh -c php -r "co                                                                                               py('https://getcomposer.org/installer', 'composer-setup.php');" &&     php -r "i                                                                                               f (hash_file('SHA384', 'composer-setup.php') === '${composer_hash}') { echo 'Ins                                                                                               taller verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'                                                                                               ); } echo PHP_EOL;" &&     php composer-setup.php --install-dir=/usr/bin --filen                                                                                               ame=composer &&     php -r "unlink('composer-setup.php');"' returned a non-zero  

Any idea how to solve it?

**Comment by aaroncox** [comment]
The hash in the dockerfile needs to be updated with the most recent version. 

The line that needs changed is here: https://github.com/aaroncox/steemdb/blob/master/docker/development/Dockerfile#L5

And you can get the current hash from the composer website
