### ISSUE TITLE
Unfollow shows as Follow

### ISSUE THREAD

**Issue by KrNel** [aaroncox/steemdb#9]
I had an unfollow, but it's marked as a Follow on the Followers section of steemdb.com. Thanks.

**Comment by KrNel** [comment]
![unfollow-as-follow](https://cloud.githubusercontent.com/assets/308183/22156613/0db8c686-df02-11e6-8552-c595c2b6f5a2.png)

**Comment by aaroncox** [comment]
Looks like the json structure changed, I'll get it updated and working again.
